-- CRIAR HOSPITAL
CREATE TABLE TBL_HOSPITAL
	(ID_HOSP NUMERIC,
		NOME VARCHAR(255),
		ENDERECO VARCHAR(255),
		BAIRRO VARCHAR(255),
		CEP VARCHAR(255),
		CNPJ VARCHAR(255),
		CIDADE VARCHAR(255),
		ESTADO VARCHAR(255),
		CONSTRAINT HOSPITAL_PK PRIMARY KEY(ID_HOSP));
-- CRIAR PACIENTE
CREATE TABLE TBL_PACIENTE
	(ID_PACIENTE NUMERIC,
		NOME_PACIENTE VARCHAR(255),
		EMAIL VARCHAR(255),
		RG VARCHAR(255),
		CPF VARCHAR(255),
		CARTAO_SUS VARCHAR(255),
		ENDERECO_PACIENTE VARCHAR(255),
		ID_SENHA(255),
		CONSTRAINT PACIENTE_PK PRIMARY KEY (ID_PACIENTE));

CREATE TABLE TBL_USUARIOS
	(ID_USUARIO NUMERIC,
		PWD VARCHAR(255),
		TIPO_ACESSO(255)
		CONSTRAINT uSUARIO_PK PRIMARY KEY (ID_USUARIO));

ALTER TABLE TBL_PACIENTE
	ADD CONSTRAINT CPF_UNICO
	UNIQUE (CPF);

